services:
  redis:
    image: redis:7-alpine
    container_name: whatsapp-redis
    ports:
      - "6381:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

  whatsapp-ai-api:
    build: .
    container_name: whatsapp-ai-api
    env_file:
      - .env
    ports:
      - "8003:8000"
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

volumes:
  redis_data: 